### ISSUE TITLE
GRAFIMO repeatedly extracting regions from graph for each motif

### ISSUE THREAD

**Issue by cgroza** [pinellolab/GRAFIMO#4]
Hi,

I am trying to use GRAFIMO to scan multiple motifs in a genome graph.
I passed in a MEME file with roughly 300 motifs defined in it.
The tools works fine, but every time it finishes with one motif in the file and moves to the next one, it re-extracts all the regions defined in the BED file.
I am not sure it is necessary for the tool to do that, and maybe this time costly step could be avoided?

Here is an example of the output logs I am getting:
```
***************************************************************************

        Welcome to GRAFIMO v1.1.4

***************************************************************************

Read 344 motifs in motifs.meme

Processing motifs

Progress: [==================================================] 100.0% Complete

Extracting regions defined in regions.bed.

Progress: [==================================================] 100.0% Complete
Scoring hits for motif +MA0816.1.
Scoring hits for motif -MA0816.1.

Progress: [==================================================] 100.0% Complete

Computing q-values...

Scanned sequences:      136064
Scanned nucleotides:    1360640

Writing results in epi_motifs.


Extracting regions defined in regions.bed.

Progress: [                                                  ] 0.0% Complete
Progress: [==================================================] 100.0% Complete
Scoring hits for motif +MA1632.1.
Scoring hits for motif -MA1632.1.

Progress: [==================================================] 100.0% Complete
...
```

**Comment by lucapinello** [comment]
Hi Cristian,

Thanks for trying Grafimo and for the suggestion.

 I have CCed Manuel, the main developer of GRAFIMO so he can consider
improving this part.

Thanks,

Luca

**Comment by ManuelTgn** [comment]
Hi Cristian,

Thanks for considering GRAFIMO for your research and for the suggestion.

I think that we can improve the regions extraction step and avoid to repeat that operation for each motif in your MEME file.
I just opened a new branch `extract_regions` in GRAFIMO's repo () where I'll put some updates to the code to speed-up this step.

Let us know if you have other requests or ideas to improve GRAFIMO. 

Thanks,

Manuel

**Comment by cgroza** [comment]
Thank you,
Otherwise, this tool is great and very fast. I can see it easily screening hundreds of motifs.

**Comment by ManuelTgn** [comment]
Hi Cristian,

now GRAFIMO visits the VG only one time, without restarting the scan for each motif in the MEME file.
In my test cases,  I observed  a significant speed-up.

Feel free to suggest further improvements to our tool!

Manuel
